# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 092fc650439d8f1123a7fbc69ffa8453f3ce0960c95789198e726d7c0195f52e0f370106f6b7d237babfe2a75c9c34bf8945323996ba037e40b324dffd9b8b9a

test:
  secret_key_base: 3933265b4875220b9b3da979ead5b28e262d132dc4fc5776dd23e829aea1ca163caf013ffe6928af42c9c0795aef4a4473e91763589089407f1ba45247aad64e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
